name: Deploy Laravel to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # (เพิ่มขั้นตอนสร้าง .env ถ้าต้องการ)

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, ctype, json, tokenizer, mongodb, redis
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/laravel

            php artisan down

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear
            php artisan route:clear

            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            php artisan up
